# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: rsync Snapshot Backup
version: 1.0.2
slug: rsync_snapshot_backup
description: Automatically create HomeAssistant snapshots and backup to remote server using rsync
url: https://github.com/Sarabveer/rsync-snapshot-backup/tree/master/README.md
init: false
startup: once
boot: manual
host_network: true
backup: hot
arch:
- aarch64
- amd64
- armhf
- armv7
- i386
hassio_api: true
hassio_role: backup
map:
- backup:ro
options:
  rsync_host: ''
  rsync_user: ''
  rsync_password: ''
  remote_directory: ''
  keep_local_backup: ''
  snapshot_password: ''
  supervisor_token: ''
schema:
  rsync_host: str
  rsync_user: str
  rsync_password: str
  remote_directory: str
  keep_local_backup: match(^(all|[+]?\d*)$)
  snapshot_password: "str?"
  supervisor_token: "str?"
